Repository bastionzero/webshell-common-ts, pull requests merged in 2022-11, with the labels that each got.

#99 Move agent interfaces to separate files
  http/v2/target/bzero/requests/bzero-agent.requests.ts
  http/v2/target/bzero/requests/generic-agent.requests.ts
  http/v2/target/bzero/requests/restart-agent.requests.ts
  http/v2/target/bzero/requests/retrieve-agent-logs.requests.ts
Labels: refactor

#102 Add KubeConnectionSummary type
  http/v2/connection/types/kube-connection-summary.types.ts
Labels: enhancement

#94 Service accounts [CWC-2056]
  http/v2/common.types/subject.types.ts
  http/v2/event/requests/command-event-filter.requests.ts
  http/v2/event/requests/connection-event-filter.requests.ts
  http/v2/event/requests/user-event-filter.requests.ts
  http/v2/event/types/command-event-data-message.ts
  http/v2/event/types/connection-event-data-message.ts
  http/v2/event/types/user-event-data-message.types.ts
  http/v2/service-account/requests/configure-service-account.requests.ts
  http/v2/service-account/requests/create-service-account.requests.ts
  http/v2/service-account/requests/login-service-account.requests.ts
  http/v2/service-account/requests/update-service-account.requests.ts
  http/v2/service-account/responses/create-service-account.responses.ts
  http/v2/service-account/types/service-account-configuration.types.ts
  http/v2/service-account/types/service-account-summary.types.ts
  http/v2/subject/requests/update-subject.requests.ts
  http/v2/subject/types/subject-role.types.ts
  http/v2/subject/types/subject-summary.types.ts
  http/v2/user/requests/update-user.requests.ts
Labels: Feature Branch, refactor
