Repository bastionzero/webshell-common-ts, pull requests merged in 2022-07, with the labels that each got.

#78 [Feat: FUD] Add scpOnly flag to universal connection response
  http/v2/connection/responses/create-universal-connection.response.ts
  http/v2/policy-query/responses/tunnels.response.ts
Labels: Feature Branch

#81 Distinguish targets by environment
  http/v2/connection/requests/create-universal-connection.request.ts
  http/v2/event/response/command-event-data-message.ts
  http/v2/event/response/connection-event-data-message.ts
  http/v2/event/response/kube-event-data-message.ts
  http/v2/event/types/command-event-data-message.ts
  http/v2/event/types/connection-event-data-message.ts
Labels: Feature Branch

#80 Add BZCert Validation Info to Keysplitting Zli Config
  http/v2/organization/types/organization-bzcert-validation-info.types.ts
  keysplitting.service/keysplitting.service.ts
  keysplitting.service/keysplitting.service.types.ts
Labels: enhancement

#83 Add typescript semicolon lint rule to eslint
  .eslintrc.json
  autodiscovery-script/autodiscovery-script.types.ts
Labels: refactor
