Repository bastionzero/webshell-common-ts, pull requests merged in 2022-08, with the labels that each got.

#84 clear keysplitting config
  keysplitting.service/keysplitting.service.ts
Labels: bug

#82 Just in Time Access [CWC-1661]
  http/v2/organization/requests/add-slack-integration.requests.ts
  http/v2/organization/responses/slack-sdk-integration.response.ts
  http/v2/organization/types/SlackSDKTeam.ts
  http/v2/organization/types/slack-integration-summary.types.ts
  http/v2/policy/just-in-time/requests/just-in-time-policy-create.requests.ts
  http/v2/policy/just-in-time/requests/just-in-time-policy-update.requests.ts
  http/v2/policy/just-in-time/types/just-in-time-policy-summary.types.ts
  http/v2/policy/types/base-policy-summary.types.ts
  http/v2/policy/types/policy-type.types.ts
  http/v2/policy/types/policy.types.ts
Labels: Feature Branch

#86 Distinguish targets by environment for `SSH`
  http/v2/connection/requests/create-universal-ssh-connection.request.ts
  http/v2/policy-query/responses/tunnels.response.ts
Labels: enhancement

#89 Add messages for agent failsafe and recovery
  http/v2/event/types/agent-status-change-data.types.ts
  http/v2/target/bzero/requests/restart-bzero-agent.requests.ts
Labels: enhancement
